# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8192e50d579ad9e802e21c2115aafbf782e924f6b719297076c46ef643893f7c2d33a9748a7f1031ab437a03fa10cfbeaed2b3c08dc2d001df9ff8ba875dd3e0

test:
  secret_key_base: 05757535373a5634be953680994c3ac5ab3973eb8ba87fa9ce2421c5494379aaa56d067bd4381ccc095f23a8ebbafae12ae020487609277c915eb90a388dbf5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
